IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUBCATEGORY')
	DROP TABLE SUBCATEGORY
GO
CREATE TABLE dbo.SUBCATEGORY
	(
	SUBCATEGORYID int NOT NULL,
	SUBCATEGORYNAME varchar(50) NOT NULL,
	CATEGORYID int NOT NULL,
	ISACTIVE bit NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.SUBCATEGORY ADD CONSTRAINT
	PK_SUBCATEGORY PRIMARY KEY CLUSTERED 
	(
	SUBCATEGORYID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.SUBCATEGORY ADD CONSTRAINT
	FK_SUBCATEGORY_CATEGORY FOREIGN KEY
	(
	CATEGORYID
	) REFERENCES dbo.CATEGORY
	(
	CATEGORYID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.SUBCATEGORY SET (LOCK_ESCALATION = TABLE)
