CREATE TABLE [dbo].[USER](
	[USERID] [int] NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[USEREMAIL] [varchar](50) NOT NULL,
	[USERPASS] [varchar](50) NOT NULL,
	[ROLEID] [int] NOT NULL,
	[ISACTIVE] [bit] NOT NULL,
	[SETDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_ROLE] FOREIGN KEY([ROLEID])
REFERENCES [dbo].[ROLE] ([ROLEID])
GO

ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_ROLE]



